import org.lovetropics.multimedia.NativeBuildPlatform

plugins {
    id 'idea'
    id 'java-library'
    id 'io.github.goooler.shadow' version '8.1.8'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'maven-publish'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

group = group_id
version = mod_version

def env = System.getenv()
if (env.GITHUB_RUN_NUMBER) {
    version = "$mod_version.${env.GITHUB_RUN_NUMBER}"
} else {
    version = "$mod_version.0-SNAPSHOT"
}

ext {
    if (env.GITHUB_RUN_NUMBER) {
        libVersion = "$project.lib_version.${env.GITHUB_RUN_NUMBER}"
    } else {
        libVersion = "$project.lib_version.0-SNAPSHOT"
    }
}

neoForge {
    version = project.neo_version

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.WARN
            gameDirectory = project.file('run')
        }
        client {
            client()
            ideName = 'NeoForge Client'
        }
        server {
            server()
            ideName = 'NeoForge Server'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    shade
    implementation.extendsFrom shade
    additionalRuntimeClasspath.extendsFrom shade
    shadeNative
    runtimeOnly.extendsFrom shadeNative
    additionalRuntimeClasspath.extendsFrom shadeNative
}

repositories {
    maven {
        url = 'https://maven.gegy.dev/releases'
        content {
            includeGroup 'org.lovetropics'
        }
    }
    mavenLocal()
}

dependencies {
    shade project(':lib')
    if (env.CROSS_PLATFORM_BUILD) {
        NativeBuildPlatform.values().each { final platform ->
            final def nativeFile = platform.getArtifactFile(layout.projectDirectory, 'multimedia-lib', project.ext.libVersion)
            shadeNative files(nativeFile.path)
        }
    } else {
        shadeNative project(':lib:native')
    }

    jarJar(implementation("org.lovetropics:LTLib:$ltlib_version"))
}

tasks.named('jar', Jar).configure {
    archiveClassifier = 'slim'
}

tasks.named('build').configure {
    dependsOn shadowJar
}

shadowJar {
    configurations = [project.configurations.shade, project.configurations.shadeNative]
    archiveClassifier = ''
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata

neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            artifact shadowJar
        }
    }

    repositories {
        if (env.MAVEN_URL) {
            maven {
                credentials {
                    username env.MAVEN_USERNAME
                    password env.MAVEN_PASSWORD
                }
                url env.MAVEN_URL
            }
        } else {
            mavenLocal()
        }
    }
}
