plugins {
    id 'java-library'
}

group = group_id
version = rootProject.ext.libVersion

base {
    archivesName = 'multimedia-lib'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "org.jspecify:jspecify:$jspecify_version"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
